CREATE TABLE users (
    id iNTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT NOT NULL,
    acct_created TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO users (username)
VALUES
    ('demo_user'),
    ('oliver'),
    ('kentledge'),
    ('kokoproject'),
    ('petrifiedsteam'),
    ('peterswanson'),
    ('mushroomhouse'),
    ('owlette'),
    ('marshall'),
    ('baby'),
    ('grogu'),
    ('spike'),
    ('lark');